Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['^\s*#']
  Exclude:
    - "config/initializers/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

# The guiding principle of classes is SRP, SRP can't be accurately measured by LoC
Metrics/ClassLength:
  Max: 1500

# compatibility with rufo
Style/StringLiterals:
  EnforcedStyle: double_quotes
